import type {Metadata} from "next";
import {Inter} from "next/font/google";
import ThemeRegistry from "./ThemeRegistry";
import "./globals.css";

const inter = Inter({subsets: ["latin"]});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app"
};

const RootLayout = ({children}: {children: React.ReactNode}) => {
	return (
		<html lang="en">
			<body className={inter.className}>
				<ThemeRegistry options={{key: "mui"}}>{children}</ThemeRegistry>
			</body>
		</html>
	);
};

export default RootLayout;
